import type { Word } from "./types";

const w = (thai: string, ipa: string, vi: string, en: string, parts?: string[]): Word => ({ thai, ipa, meaning: { vi, en }, parts });

/** Từ điển mẫu. Có thể thay bằng API (xem api/queries.ts). */
export const WORDS: Word[] = [
  // Từ đơn
  w("กา", "kaː", "con quạ", "crow"),
  w("ขา", "kʰǎː", "cái chân", "leg"),
  w("ข่า", "kʰàː", "củ riềng", "galangal"),
  w("ค่า", "kʰâː", "giá trị, chi phí", "value, cost"),
  w("ค้า", "kʰáː", "buôn bán", "to trade"),
  w("คา", "kʰaː", "mắc kẹt", "stuck"),
  w("มา", "maː", "đến", "to come"),
  w("ม้า", "máː", "con ngựa", "horse"),
  w("หมา", "mǎː", "con chó", "dog"),
  w("นา", "naː", "ruộng lúa", "rice field"),
  w("หน้า", "nâː", "mặt; trang", "face; page"),
  w("น้า", "náː", "dì, cậu (em của mẹ)", "mother’s younger sibling"),
  w("ตา", "taː", "mắt; ông ngoại", "eye; maternal grandfather"),
  w("ปลา", "plaː", "con cá", "fish"),
  w("ยา", "jaː", "thuốc", "medicine"),
  w("ป้า", "pâː", "bác gái", "aunt (older than parent)"),
  w("ป่า", "pàː", "rừng", "forest"),
  w("ฟ้า", "fáː", "bầu trời", "sky"),
  w("ห้า", "hâː", "năm (số 5)", "five"),
  w("ช้า", "tɕʰáː", "chậm", "slow"),
  w("ชา", "tɕʰaː", "trà", "tea"),
  w("ขวา", "kʰwǎː", "bên phải", "right (side)"),
  w("ปู", "puː", "con cua", "crab"),
  w("งู", "ŋuː", "con rắn", "snake"),
  w("หนู", "nǔː", "con chuột", "mouse, rat"),
  w("หมู", "mǔː", "con lợn", "pig"),
  w("ดู", "duː", "xem, nhìn", "to look, watch"),
  w("รู", "ruː", "cái lỗ", "hole"),
  w("รู้", "rúː", "biết", "to know"),
  w("ครู", "kʰruː", "thầy cô giáo", "teacher"),
  w("อยู่", "jùː", "ở", "to be at, live"),
  w("ดี", "diː", "tốt", "good"),
  w("สี", "sǐː", "màu", "color"),
  w("สี่", "sìː", "bốn", "four"),
  w("ปี", "piː", "năm (thời gian)", "year"),
  w("ผี", "pʰǐː", "con ma", "ghost"),
  w("มี", "miː", "có", "to have"),
  w("ที่", "tʰîː", "ở, chỗ", "at; place"),
  w("พี่", "pʰîː", "anh, chị", "older sibling"),
  w("นี้", "níː", "này", "this"),
  w("พ่อ", "pʰɔ̂ː", "bố", "father"),
  w("หมอ", "mɔ̌ː", "bác sĩ", "doctor"),
  w("แม่", "mɛ̂ː", "mẹ", "mother"),
  w("แพ", "pʰɛː", "cái bè", "raft"),
  w("แก่", "kɛ̀ː", "già", "old (age)"),
  w("ไก่", "kàj", "con gà", "chicken"),
  w("ไข่", "kʰàj", "quả trứng", "egg"),
  w("ใจ", "tɕaj", "trái tim, lòng", "heart, mind"),
  w("ไป", "paj", "đi", "to go"),
  w("ใน", "naj", "trong", "in"),
  w("ให้", "hâj", "cho", "to give"),
  w("ไฟ", "faj", "lửa, đèn", "fire, light"),
  w("ไม่", "mâj", "không", "not"),
  w("ใหม่", "màj", "mới", "new"),
  w("ใส", "sǎj", "trong suốt", "clear"),
  w("ไหม", "mǎj", "…không? (tiểu từ hỏi); lụa", "question particle; silk"),
  w("ใคร", "kʰraj", "ai", "who"),
  w("ไกล", "klaj", "xa", "far"),
  w("ใกล้", "klâj", "gần", "near"),
  w("เรา", "raw", "chúng ta", "we"),
  w("เขา", "kʰǎw", "anh ấy, họ; núi", "he, they; mountain"),
  w("เข่า", "kʰàw", "đầu gối", "knee"),
  w("เข้า", "kʰâw", "vào", "to enter"),
  w("เต่า", "tàw", "con rùa", "turtle"),
  w("เมา", "maw", "say", "drunk"),
  w("เก้า", "kâw", "chín", "nine"),
  w("น้ำ", "náːm", "nước", "water"),
  w("ทำ", "tʰam", "làm", "to do, make"),
  w("จำ", "tɕam", "nhớ", "to remember"),
  w("ดำ", "dam", "màu đen", "black"),
  w("ต่ำ", "tàm", "thấp", "low"),
  w("คำ", "kʰam", "từ, lời", "word"),
  w("ข้าว", "kʰâːw", "cơm, gạo", "rice"),
  w("ขาว", "kʰǎːw", "trắng", "white"),
  w("ยาว", "jaːw", "dài", "long"),
  w("สาว", "sǎːw", "cô gái", "young woman"),
  w("ดาว", "daːw", "ngôi sao", "star"),
  w("หนาว", "nǎːw", "lạnh", "cold"),
  w("แมว", "mɛːw", "con mèo", "cat"),
  w("ซ้าย", "sáːj", "bên trái", "left (side)"),
  w("ควาย", "kʰwaːj", "con trâu", "buffalo"),
  w("หลาย", "lǎːj", "nhiều", "many"),
  w("ปลาย", "plaːj", "đầu mút, cuối", "tip, end"),
  w("ทราย", "saːj", "cát", "sand"),
  w("ร้อย", "rɔ́ːj", "một trăm", "hundred"),
  w("กิน", "kin", "ăn", "to eat"),
  w("บิน", "bin", "bay", "to fly"),
  w("ดิน", "din", "đất", "soil, earth"),
  w("หิน", "hǐn", "hòn đá", "stone"),
  w("จริง", "tɕiŋ", "thật", "true, real"),
  w("หญิง", "jǐŋ", "phụ nữ", "woman"),
  w("ฟัน", "fan", "cái răng", "tooth"),
  w("วัน", "wan", "ngày", "day"),
  w("กัน", "kan", "nhau", "each other"),
  w("มัน", "man", "nó; củ khoai", "it; tuber"),
  w("ฝัน", "fǎn", "giấc mơ, mơ", "dream"),
  w("พัน", "pʰan", "một nghìn", "thousand"),
  w("หลัง", "lǎŋ", "sau; cái lưng", "behind; back"),
  w("หนัง", "nǎŋ", "phim; da", "movie; skin"),
  w("รัก", "rák", "yêu", "to love"),
  w("กลับ", "klàp", "quay về", "to return"),
  w("สิบ", "sìp", "mười", "ten"),
  w("คน", "kʰon", "người", "person"),
  w("ผม", "pʰǒm", "tóc; tôi (nam)", "hair; I (male)"),
  w("ลม", "lom", "gió", "wind"),
  w("นม", "nom", "sữa", "milk"),
  w("ส้ม", "sôm", "quả cam", "orange"),
  w("ตรง", "troŋ", "thẳng", "straight"),
  w("รถ", "rót", "xe", "vehicle, car"),
  w("มด", "mót", "con kiến", "ant"),
  w("นก", "nók", "con chim", "bird"),
  w("หก", "hòk", "sáu", "six"),
  w("พระ", "pʰráʔ", "nhà sư", "monk"),
  w("จะ", "tɕàʔ", "sẽ", "will (future)"),
  w("ปาก", "pàːk", "miệng", "mouth"),
  w("มาก", "mâːk", "nhiều, rất", "very, a lot"),
  w("หมาก", "màːk", "quả cau", "betel nut"),
  w("อยาก", "jàːk", "muốn", "to want"),
  w("ขาด", "kʰàːt", "rách; thiếu", "torn; lacking"),
  w("ทราบ", "sâːp", "biết (trang trọng)", "to know (formal)"),
  w("ลูก", "lûːk", "con (của cha mẹ)", "child (offspring)"),
  w("พูด", "pʰûːt", "nói", "to speak"),
  w("จูบ", "tɕùːp", "hôn", "to kiss"),
  w("ชอบ", "tɕʰɔ̂ːp", "thích", "to like"),
  w("บอก", "bɔ̀ːk", "bảo, nói với", "to tell"),
  w("ออก", "ʔɔ̀ːk", "ra", "to exit"),
  w("นอน", "nɔːn", "ngủ, nằm", "to sleep, lie down"),
  w("ร้อน", "rɔ́ːn", "nóng", "hot"),
  w("สอง", "sɔ̌ːŋ", "hai", "two"),
  w("น้อง", "nɔ́ːŋ", "em", "younger sibling"),
  w("สาม", "sǎːm", "ba", "three"),
  w("ความ", "kʰwaːm", "(tiền tố tạo danh từ)", "(noun-forming prefix)"),
  w("ล้าน", "láːn", "một triệu", "million"),
  w("กลาง", "klaːŋ", "ở giữa", "middle"),
  w("สร้าง", "sâːŋ", "xây dựng", "to build"),
  w("อย่าง", "jàːŋ", "kiểu, loại", "kind, manner"),
  w("อย่า", "jàː", "đừng", "don’t"),
  w("แดง", "dɛːŋ", "màu đỏ", "red"),
  w("แรง", "rɛːŋ", "mạnh", "strong"),
  w("แปรง", "prɛːŋ", "bàn chải", "brush"),
  w("แปด", "pɛ̀ːt", "tám", "eight"),
  w("แข็ง", "kʰɛ̌ŋ", "cứng", "hard"),
  w("เล็ก", "lék", "nhỏ", "small"),
  w("เด็ก", "dèk", "trẻ con", "child"),
  w("เป็ด", "pèt", "con vịt", "duck"),
  w("เจ็ด", "tɕèt", "bảy", "seven"),
  w("เพลง", "pʰleːŋ", "bài hát", "song"),
  w("หนึ่ง", "nɯ̀ŋ", "một", "one"),
  w("คืน", "kʰɯːn", "đêm", "night"),
  w("หรือ", "rɯ̌ː", "hoặc", "or"),
  w("เดิน", "dɤːn", "đi bộ", "to walk"),
  w("เงิน", "ŋɤn", "tiền; bạc", "money; silver"),
  w("เปิด", "pɤ̀ːt", "mở", "to open"),
  w("เกิด", "kɤ̀ːt", "sinh ra", "to be born"),
  w("เมือง", "mɯaŋ", "thành phố, xứ", "city, country"),
  w("เรือ", "rɯa", "con thuyền", "boat"),
  w("เสือ", "sɯ̌a", "con hổ", "tiger"),
  w("เกลือ", "klɯa", "muối", "salt"),
  w("เมีย", "mia", "vợ", "wife"),
  w("เรียน", "rian", "học", "to study"),
  w("เขียน", "kʰǐan", "viết", "to write"),
  w("เสีย", "sǐa", "hỏng; mất", "broken; to lose"),
  w("วัว", "wua", "con bò", "cow"),
  w("หัว", "hǔa", "cái đầu", "head"),
  w("ตัว", "tua", "thân mình; con (loại từ)", "body; classifier for animals"),
  w("กลัว", "klua", "sợ", "to be afraid"),
  w("ขวด", "kʰùat", "cái chai", "bottle"),
  w("ทา", "tʰaː", "bôi, quét", "to apply, paint"),

  // Ví dụ cho phần nguyên âm biến hình
  w("เตะ", "tèʔ", "đá (bằng chân)", "to kick"),
  w("เต็ม", "tem", "đầy", "full"),
  w("มือ", "mɯː", "bàn tay", "hand"),
  w("มืด", "mɯ̂ːt", "tối", "dark"),
  w("เลาะ", "lɔ́ʔ", "men theo", "to go along (an edge)"),
  w("ล็อก", "lɔ́k", "khoá (từ mượn “lock”)", "to lock (loanword)"),
  w("เลย", "lɤːj", "luôn, hẳn; vì vậy", "at all; so, then"),
  w("เรือน", "rɯan", "ngôi nhà", "house, dwelling"),
  w("สวน", "sǔan", "khu vườn", "garden"),
  w("เล่น", "lên", "chơi", "to play"),
  // Từ ghép
  w("ภาษา", "pʰaː.sǎː", "ngôn ngữ", "language", ["ภา", "ษา"]),
  w("แม่น้ำ", "mɛ̂ː.náːm", "dòng sông", "river", ["แม่", "น้ำ"]),
  w("น้ำตา", "náːm.taː", "nước mắt", "tears", ["น้ำ", "ตา"]),
  w("หน้าตา", "nâː.taː", "diện mạo", "looks, appearance", ["หน้า", "ตา"]),
  w("ไฟฟ้า", "faj.fáː", "điện", "electricity", ["ไฟ", "ฟ้า"]),
  w("รถไฟ", "rót.faj", "tàu hoả", "train", ["รถ", "ไฟ"]),
  w("ไข่ไก่", "kʰàj.kàj", "trứng gà", "chicken egg", ["ไข่", "ไก่"]),
  w("ลูกสาว", "lûːk.sǎːw", "con gái", "daughter", ["ลูก", "สาว"]),
  w("พี่น้อง", "pʰîː.nɔ́ːŋ", "anh chị em", "siblings", ["พี่", "น้อง"]),
  w("พ่อแม่", "pʰɔ̂ː.mɛ̂ː", "bố mẹ", "parents", ["พ่อ", "แม่"]),
  w("ข้าวมันไก่", "kʰâːw.man.kàj", "cơm gà Hải Nam", "Hainanese chicken rice", ["ข้าว", "มัน", "ไก่"]),
  w("ดีใจ", "diː.tɕaj", "vui mừng", "glad", ["ดี", "ใจ"]),
  w("ใจดี", "tɕaj.diː", "tốt bụng", "kind-hearted", ["ใจ", "ดี"]),
  w("เข้าใจ", "kʰâw.tɕaj", "hiểu", "to understand", ["เข้า", "ใจ"]),
  w("หัวใจ", "hǔa.tɕaj", "trái tim", "heart", ["หัว", "ใจ"]),
  w("วันนี้", "wan.níː", "hôm nay", "today", ["วัน", "นี้"]),
  w("ไม่มี", "mâj.miː", "không có", "to not have", ["ไม่", "มี"]),
  w("เรียนรู้", "rian.rúː", "học hỏi", "to learn", ["เรียน", "รู้"]),
  w("ความรัก", "kʰwaːm.rák", "tình yêu", "love (noun)", ["ความ", "รัก"]),
  w("น้ำแข็ง", "náːm.kʰɛ̌ŋ", "nước đá", "ice", ["น้ำ", "แข็ง"]),
  w("สีแดง", "sǐː.dɛːŋ", "màu đỏ", "the color red", ["สี", "แดง"]),
  w("นกฮูก", "nók.hûːk", "con cú", "owl", ["นก", "ฮูก"]),
  w("หมาป่า", "mǎː.pàː", "chó sói", "wolf", ["หมา", "ป่า"]),
  w("ปากกา", "pàːk.kaː", "bút bi", "pen", ["ปาก", "กา"]),
  w("หมอฟัน", "mɔ̌ː.fan", "nha sĩ", "dentist", ["หมอ", "ฟัน"]),
  w("แปรงฟัน", "prɛːŋ.fan", "đánh răng", "to brush teeth", ["แปรง", "ฟัน"]),
  w("กลางวัน", "klaːŋ.wan", "ban ngày", "daytime", ["กลาง", "วัน"]),
  w("กลางคืน", "klaːŋ.kʰɯːn", "ban đêm", "night-time", ["กลาง", "คืน"]),
  w("เสือดาว", "sɯ̌a.daːw", "báo hoa mai", "leopard", ["เสือ", "ดาว"]),
  w("วัวนม", "wua.nom", "bò sữa", "dairy cow", ["วัว", "นม"]),
  w("หลังคา", "lǎŋ.kʰaː", "mái nhà", "roof", ["หลัง", "คา"]),
  w("ลูกค้า", "lûːk.kʰáː", "khách hàng", "customer", ["ลูก", "ค้า"]),
  w("ดินสอ", "din.sɔ̌ː", "bút chì", "pencil", ["ดิน", "สอ"]),
  w("ทำงาน", "tʰam.ŋaːn", "làm việc", "to work", ["ทำ", "งาน"]),
  w("งาน", "ŋaːn", "công việc; lễ hội", "work; event"),
];
